# Generated by Django 5.0.1 on 2024-01-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='categoria',
            field=models.ManyToManyField(error_messages={'Selecione uma ou mais categorias!'}, to='flashcard.categoria'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='quantidade_perguntas',
            field=models.IntegerField(error_messages={'Adicione uma ou mais perguntas'}),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='titulo',
            field=models.CharField(error_messages={'Selecione um titulo'}, max_length=100),
        ),
    ]
