# Generated by Django 5.0.1 on 2024-01-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_alter_desafio_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='quantidade_perguntas',
            field=models.IntegerField(default=1, error_messages={'Adicione uma ou mais perguntas'}),
        ),
    ]
