# Generated by Django 5.0.1 on 2024-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_desafio_quantidade_perguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='categoria',
            field=models.ManyToManyField(error_messages={'blank': 'Selecione uma ou mais categorias!', 'null': 'Selecione uma ou mais categorias.'}, to='flashcard.categoria'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='quantidade_perguntas',
            field=models.IntegerField(default=1, error_messages={'blank': 'Adicione uma ou mais perguntas', 'null': 'Selecione uma ou mais perguntas.'}),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='titulo',
            field=models.CharField(error_messages={'blank': 'Selecione um titulo', 'null': 'Selecione um título.'}, max_length=100),
        ),
    ]
